project_id = "lkxgjlojvkyxeiaapqgt"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lkxgjlojvkyxeiaapqgt.supabase.co"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[db]
port = 54322

[storage]
enabled = true
port = 54323
file_size_limit = "50MB"

[functions.chat-ai]
verify_jwt = true

[edge_runtime]
ip_version = "ipv4"