// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkxgjlojvkyxeiaapqgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxreGdqbG9qdmt5eGVpYWFwcWd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzAyOTcsImV4cCI6MjA2NDgwNjI5N30.0NbgIh2NSq7R0uA5jQSYkejWpOu9tuviJZVWapXBm0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);